baseURL : 
languageCode : "en-us"
title : "Abhijan Wasti"
theme : "hugo-profile"

Menus:
  main:
    - identifier: blog
      name: Posts
      title: Posts
      url: "/posts/"
      weight: 1
    
    - identifier: gallery
      name: Gallery
      title: Gallery
      url: "/gallery/"
      weight: 2

# Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Abhijan Wasti"
  description: Personal Website
  # staticPath: ""  # The path to serve the static files from
  favicon: "/icons/favicon.ico"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: Hi! I am
    title: "Abhijan Wasti"
    subtitle: Machine Learning | Eye Tracking 
    content:
          "
          - Background in imaging science and electronics and communication engineering.

          - Currently working towards a graduate degree at RIT.

          - Strong interest in the intersection of technology and art.

          - Open to internships and job offers
          "
    image: /images/Abhijan Wasti.jpg
    button:
      enable: true
      name: "Resume"
      url: https://drive.google.com/file/d/1YWqIRkIYzRQADUfLNopacfMVhYojNkwt/view?usp=sharing
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/blurryface5178
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/abhijan-wasti-85978a145/
        - icon: fas fa-envelope
          url: "mailto:abhijanwasti@gmail.com"

  # About
  about:
    enable: true
    title: "Skills"
    image: 
    content: 
    skills:
      enable: true
      items:
        - "**Programming Languages:**  Python | C | C++ | MATLAB | Javascript | HTML | CSS"
        - "**Frameworks:** OpenCV | sklearn | PyTorch "
        - "**Softwares:** Blender | Pupil Core"
        - "**Online Courses:** "

  # Experience
  experience:
    enable: true
    index: false
    items:
      - job: "Research Assistant"
        company: 
          name: "Rochester Institute of Technology"
          url: "https://www.rit.edu/science/multidisciplinary-vision-research-laboratory"
        date: "Aug 2021 - Present"
        featuredLink:
          enable: false
          name: "Sentiment Classifier"
          url: "https://github.com/blurryface5178/Sentiment-Classifier"
        content: 
                "- Improving current eye tracking technology for better gaze estimation. Details [here](blogs/rit/).

                - Completed responsibilities as a TA with a pass rate of 87%"

      - job: "Machine Learning Intern"
        company: 
          name: "FuseMachines Inc."
          url: "https://fusemachines.com/"
        date: "May 2021 - Aug 2021"
        featuredLink:
          enable: true
          name: "Sentiment Classifier"
          url: "https://github.com/blurryface5178/Sentiment-Classifier"
        content:
                "- Reviewed and implemented techniques in exploratory data analysis and data visualization

                  - Worked with libraries such as numpy, pandas and matplotlib for statistical analysis and modeling

                  - Reviewed and implemented machine learning pipeline and deep learning architecture

                  - Collborated with a team over git and google colab

                  - Created APIs to deploy ML models with tools such as fastapi, streamit and docker"
          
      - job: "Embedded Systems Developer"
        company: 
          name : "Machineer Technology Pvt. Ltd."
          url: "https://www.machineertech.com/"
        date: "Mar 2021 - Jul 2021"
        featuredLink:
          enable: false
          name: "Sentiment Classifier"
          url: "https://github.com/blurryface5178/Sentiment-Classifier"
        content:
                "- Designed and implemented a transformer monitoring system for the urban electricity grid

                  - Developed a prototype for an autonomous artificial environment control system for solar desiccator

                  - Developed a prototype for a low-cost sanitary pad dispenser
                  
                  - Developed a low-cost GPS-less technique for geolocation suitable for a business district"

  # Education
  education:
    enable: true
    index: false
    items:
      - title: "Master in Imaging Science"
        school:
          name: "Rochester Institute of Technology, Rochester, NY"
          url: "https://www.rit.edu/"
        date: "Present"
        courses: true
        names: " Fourier Methods for Imaging | Human Visual Systems | Radiometry \\

                Advanced Eye Tracking | Image Processing and Computer Vision | Procedural Shading"
        GPA: "3.79 / 4.0"
        # content: |-

      - title: "Bachelors in Electronics and Communication Engineering"
        school:
          name: "Tribhuwan University, Kathmandu, Nepal"
          url: "http://www.tribhuvan-university.edu.np/"
        date: "2019"
        courses: true
        names: "Image Processing and Pattern Recognition | Artificial Intelligence | Probability and Statistics | Big Data"
        # GPA: "3.9 out of 5.0"
        # content: |-
        #   I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #   - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #   - Face mask detection using a single convolutional neural network.

        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "Captsone Project: Aerial View-Based Guidance System"
          url: "https://github.com/blurryface5178/mazesolver"
        
  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Halftoner and Remover
        content: Python library with the implementation of Floyd-Steinberg error difussion and blue noise dithering as well as removal of halftone
        image: /images/projects/halftoner.jpg
        featured:
          name: Details...
          link: https://github.com/blurryface5178/halftoning
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/blurryface5178/Colora

      - title: Color 1.0
        content: Image editing app that creates unique edits
        image: /images/projects/colora.jpg
        featured:
          name: Deatils...
          link: /posts/colora
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/blurryface5178/Colora

      - title: Sentiment Classifier
        content: Sentiment classification webapp based on the 1-P-3-ISEAR dataset. Front end is handled by streamlit and the backend with a FastAPI service.
        image: /images/projects/sentiment.jpg
        featured:
          name: Details...
          link: https://github.com/blurryface5178/Sentiment-Classifier
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/blurryface5178/Sentiment-Classifier

      - title: Space Invaders!
        content: Implementation of the classic arcade game of SpaceInvaders.
        image: /images/projects/gameplay.gif
        featured:
          name: Details...
          link: https://github.com/blurryface5178/spaceinvaders
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/blurryface5178/spaceinvaders

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: abhijanwasti@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/blurryface5178
      linkedin: https://www.linkedin.com/in/abhijan-wasti-85978a145/
      email: "mailto:abhijanwasti@gmail.com"
